import Image from "next/image";
import Head from "next/head";
const about = () => {
    return (  
        <div className="about">
         
         <Head>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

          <div className="first">
            <Image src="/1.jpg" alt="pic" className="photo" width={450} height={250} />  

            <div className="second">
               <h1>A Bit About Myself</h1>
               <p>I am an I.T. gradute seeking an eventual career as a software developer. 
                  During the course of my education I learned what goes into the planning, design and
                  technical aspects of software development, as well as the testing and maintenance
                  software. My education has equipped me with the skills and expertise to effectively
                  work in teams and solve problems as a software developer. I am eager to apply these
                  skills in the working environment and improve on them even further.</p>  
            </div>             
          </div>  

          <p>On a more personal level. My hobbies include reading and film. My interests are history and politics. I enjoy hanging with my friends.
             And I have recently taken on vide game development as a hobby.  </p> 

           <h1>Why I Want Become A Developer At SOVTECH</h1>
           <p>While i have had a pretty great education I am aware that there are still many gaps in my knowledge. Things that 
              you can't learn at school or on the internet. If I want to become the software developer I know I can be; I need
              to work in an enviroment where I can be challenged, where I can work on cool and interesting projects, where I can 
              recieve mentorship and guidance.</p>  

            <p>SOVTECH seems like a place where I can get all that. Thats why it would be so awesome to work there. And on 
               top of that the graduate program justs sounds like it would be a fun expierence.
            </p>
                                      
            <h1>Education:</h1>
            <div className="education">
               <h2>Mondale High School</h2>
               <p>2015</p>
               <p>National Senior Certificate</p>
            </div>

            <div className="education">
               <h2>College of Cape Town</h2>
               <p>2018</p>
               <p>Higher Certificate in Information and Communication Technology</p>
            </div>

            <div className="education">
               <h2>Cape Peninsula University of Technology </h2>
               <p>2021</p>
               <p>Diploma in Information and Communication Technology: Applications Development</p>
            </div>   
        </div>
    );
}
 
export default about;