import Image from "next/image";
import Link from "next/link";
import Head from "next/head";

const contact = () => {
    return (     
        <div className="contact">
        <Head>
            <title>Contact</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

            <Image src="/envelope.png" alt="email" width={50} height={50} />
            <h3>Email:</h3>
            <h3>ridhaaflanders@gmail.com</h3>

            <Image src="/phone.png" alt="phone" width={50} height={50} />
            <h3>Phone:</h3> 
            <h3>081 046 0799</h3>

            <Image src="/youtube.png" alt="youtube" width={50} height={50} />
            <h3>Youtube:</h3>
            <Link href="https://www.youtube.com/channel/UCMxXs1m2gN21AUFBO6ShVbg"> <h3>https://www.youtube.com/channel/UCMxXs1m2gN21AUFBO6ShVbg</h3></Link>
           
            <Image src="/page.png" alt="youtube" width={50} height={50} />
            <h3>Resume:</h3>
            <Link href="https://docs.google.com/document/d/1f2zoR8uh6fkE9iKr9RH-xsGU_NYaeA9b/edit?usp=sharing&ouid=111263523527598274188&rtpof=true&sd=true"> <h3>Click Here</h3></Link>
            
        </div>
     );
}
 
export default contact;