import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='HBox'>
        <h1 className={styles.title}>
          Hi. I'm Ridhaa. A Developer.
        </h1>
        <h1 className="welcome">
          Welcome
        </h1>
        <p>I am a motivated software development graduate interested in improving current skillset and learning new skills.</p> 
      </div>

    </div>
  )
}
